name: Python 3.13 Demo App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python 3.13
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.13

      # 3️⃣ Cache pip packages to speed up installs
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 5️⃣ Run the app (optional, for testing)
      - name: Run demo app
        run: |
          echo "Python version:"
          python --version
          echo "Flask version:"
          python -m pip show Flask
          echo "Demo app ready!"
